
# path to aap-juce directory.
AAP_JUCE_DIR=$(shell pwd)/external/aap-juce

# path to application repo. The default is the submodule path.
APP_SRC_DIR=$(shell pwd)/external/JUCE/extras/AudioPluginHost

# base app name
APP_NAME=AudioPluginHost

# app build directory name. Usually repo name is good.
APP_BUILD_DIR=$(shell pwd)/apps/AudioPluginHost

# diff file to app, generated by git diff. "-" if there is no patch.
PATCH_FILE=$(shell pwd)/apps/juceaaphost.patch

# diff depth, depending on the nested directory in the source tree, if patch exists.
PATCH_DEPTH=3

# JUCE patches if any
JUCE_PATCHES= \
	$(shell pwd)/apps/juce-modules.patch \
	$(shell pwd)/apps/juce-modules-thread-via-dalvik.patch

# JUCE diff depth, depending on the nested directory in the source tree, if patches exist.
JUCE_PATCH_DEPTH=1

# 1 if it should skip metadata generator. Plugins need it, hosts don't.
SKIP_METADATA_GENERATOR=1


include $(AAP_JUCE_DIR)/Makefile.common
